### ISSUE TITLE
how tpot handle malware and how can i have data in map line honeymap?

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/elk#3]
Hello i have 2 questions.
1 where is malware that capture with honeypot?
2 what should i enable .in instruction about tpot on the pictures says " flags set to disable for hpfeed"
so how can i enable it and joint to honeymap?

thanks indeed

**Comment by t3chn0m4g3** [comment]
1. Depending on your persistence setting (`/data/persistence.[on,off]`) it will be kept within the hp/container subfolder within `/data` either until next container start (every 24h) or until manually removed.
2. You can find the setting in `/data/ews/conf/ews.cfg`:
```
[HPFEED]
hpfeed = false
host = 0.0.0.0
port = 0
channels = 0
ident = 0
secret= 0
```
You will need to subscribe to a [hpfeeds ](http://hpfriends.honeycloud.net/)channel.
