### ISSUE TITLE
new error :"Discover: Request Timeout after 30000ms"

### ISSUE THREAD

**Issue by jjjan** [dtag-dev-sec/elk#9]
Hello,
when i open dashboard i see this error "Discover: Request Timeout after 30000ms"
then i check Container and find out to of them is using 100 percent CPU. 
i mean honeytrap and elk use 100% CPU. so is how can i solve this issue?
is it possible to install elk in other server to correlate honeypot data?
thanks

**Comment by t3chn0m4g3** [comment]
@jjjan There might be a number of factors involved (i.e. RAM, free disk-space, traffic, etc.). Given your information all my answers would only be guesses.
However, I kindly suggest you update to [T-Pot 16.10](http://dtag-dev-sec.github.io/mediator/feature/2016/10/31/t-pot-16.10.html).

**Comment by jjjan** [comment]
great but at least we need attack map for my sensor. thanks indeed
